project_name: example
databases:
- name: duckdb-jaffle-shop
  accessors:
  - columns
  - preview
  include: []
  exclude: []
  type: duckdb
  path: ./jaffle_shop.duckdb
repos:
- name: dbt
  url: https://github.com/dbt-labs/jaffle_shop_duckdb.git
  branch: null
notion: null
llm:
    provider: openai
    api_key: "{{ env('OPENAI_API_KEY') }}"
slack: null
mcp:
  json_file_path: ./agent/mcps/mcp.json
openmetadata:
  url: http://localhost:8585
  token: "{{ env('OMD_BOT_TOKEN') }}"
  services: [jaffle_shop_postgres]
agent:
  id: "dazense://metazense.com/jaffle-shop-agent"
  omd_bot: "dazense-jaffle-agent"
