/**
 * Provision OpenMetadata bots for each agent.
 *
 * Reads agents.yml, creates an OMD bot for each agent's identity.catalog_bot,
 * and outputs JWT tokens keyed by identity.token_env.
 *
 * Usage:
 *   CATALOG_URL=http://localhost:8585 npx tsx scripts/provision-bots.ts ../scenario/travel
 *   CATALOG_URL=http://localhost:8585 npx tsx scripts/provision-bots.ts ../scenario/travel --output .env.tokens
 *
 * Prerequisites:
 *   - OpenMetadata running at CATALOG_URL
 *   - Admin credentials (default: admin@open-metadata.org / admin)
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';
import { parse as parseYaml } from 'yaml';

const ADMIN_EMAIL = process.env.OMD_ADMIN_EMAIL ?? 'admin@open-metadata.org';
const ADMIN_PASSWORD = process.env.OMD_ADMIN_PASSWORD ?? 'admin';

interface AgentIdentity {
	catalog_bot: string;
	token_env: string;
}

async function getAdminToken(baseUrl: string): Promise<string> {
	const b64Pass = Buffer.from(ADMIN_PASSWORD).toString('base64');
	const resp = await fetch(`${baseUrl}/api/v1/users/login`, {
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		body: JSON.stringify({ email: ADMIN_EMAIL, password: b64Pass }),
	});
	if (!resp.ok) {
		throw new Error(`Admin login failed: ${resp.status} ${await resp.text()}`);
	}
	const data = (await resp.json()) as { accessToken: string };
	return data.accessToken;
}

async function createBot(
	baseUrl: string,
	adminToken: string,
	botName: string,
): Promise<{ botName: string; token: string | null }> {
	const headers = {
		Authorization: `Bearer ${adminToken}`,
		'Content-Type': 'application/json',
	};

	// Check if bot user already exists
	const checkResp = await fetch(`${baseUrl}/api/v1/users/name/${botName}`, { headers });
	let userId: string;

	if (checkResp.ok) {
		const existing = (await checkResp.json()) as { id: string; name: string };
		userId = existing.id;
		console.error(`  Bot user "${botName}" already exists (${userId})`);
	} else {
		// Create bot user
		const createUserResp = await fetch(`${baseUrl}/api/v1/users`, {
			method: 'POST',
			headers,
			body: JSON.stringify({
				name: botName,
				email: `${botName}@dazense.local`,
				isBot: true,
				botType: 'Bot',
				authenticationMechanism: {
					authType: 'JWT',
					config: {},
				},
			}),
		});
		if (!createUserResp.ok) {
			const errText = await createUserResp.text();
			console.error(`  Failed to create bot user "${botName}": ${createUserResp.status} ${errText}`);
			return { botName, token: null };
		}
		const created = (await createUserResp.json()) as { id: string };
		userId = created.id;
		console.error(`  Created bot user "${botName}" (${userId})`);
	}

	// Create or get the bot entity
	const botCheckResp = await fetch(`${baseUrl}/api/v1/bots/name/${botName}`, { headers });

	if (botCheckResp.ok) {
		const bot = (await botCheckResp.json()) as {
			botUser?: { authenticationMechanism?: { config?: { JWTToken?: string } } };
		};
		const token = bot.botUser?.authenticationMechanism?.config?.JWTToken ?? null;
		if (token) {
			return { botName, token };
		}
	}

	// Create bot
	const createBotResp = await fetch(`${baseUrl}/api/v1/bots`, {
		method: 'POST',
		headers,
		body: JSON.stringify({
			name: botName,
			botUser: { id: userId, type: 'user' },
		}),
	});

	if (!createBotResp.ok) {
		const errText = await createBotResp.text();
		console.error(`  Failed to create bot "${botName}": ${createBotResp.status} ${errText}`);
		return { botName, token: null };
	}

	// Re-fetch to get the token
	const refetchResp = await fetch(`${baseUrl}/api/v1/bots/name/${botName}`, { headers });
	if (refetchResp.ok) {
		const bot = (await refetchResp.json()) as {
			botUser?: { authenticationMechanism?: { config?: { JWTToken?: string } } };
		};
		return { botName, token: bot.botUser?.authenticationMechanism?.config?.JWTToken ?? null };
	}

	return { botName, token: null };
}

async function main() {
	const scenarioPath = resolve(process.argv[2] || '../scenario/travel');
	const outputFile = process.argv.includes('--output') ? process.argv[process.argv.indexOf('--output') + 1] : null;

	const baseUrl = (process.env.CATALOG_URL ?? 'http://localhost:8585').replace(/\/$/, '');

	console.error(`Provisioning bots from: ${scenarioPath}`);
	console.error(`OpenMetadata: ${baseUrl}\n`);

	// Load agents.yml
	const agentsYaml = readFileSync(join(scenarioPath, 'agents.yml'), 'utf-8');
	const agentsConfig = parseYaml(agentsYaml) as {
		agents: Record<string, { identity: AgentIdentity }>;
	};

	// Get admin token
	const adminToken = await getAdminToken(baseUrl);
	console.error('Admin login: OK\n');

	// Create bots
	const envLines: string[] = ['# Generated by provision-bots.ts', `# ${new Date().toISOString()}`, ''];

	for (const [agentId, config] of Object.entries(agentsConfig.agents)) {
		const { catalog_bot, token_env } = config.identity;
		console.error(`Agent: ${agentId} → bot: ${catalog_bot}`);

		const result = await createBot(baseUrl, adminToken, catalog_bot);
		if (result.token) {
			envLines.push(`${token_env}=${result.token}`);
			// Never log token material — only confirm success + destination env var
			console.error(`  Token: obtained (${result.token.length} chars) → ${token_env}\n`);
		} else {
			envLines.push(`# ${token_env}= (failed to provision)`);
			console.error(`  Token: FAILED\n`);
		}
	}

	const output = envLines.join('\n') + '\n';

	if (outputFile) {
		writeFileSync(outputFile, output);
		console.error(`\nTokens written to: ${outputFile}`);
	} else {
		// Print to stdout for piping
		process.stdout.write(output);
	}
}

main().catch((err) => {
	console.error('Fatal:', err.message || err);
	process.exit(1);
});
